// Copyright (c) Facebook, Inc. and its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Data types and pure decoding for the BPF cgroup reader.
//!
//! Holds the wire record the BPF program emits, the below-side stats it decodes
//! into, the snapshot/handle the collector uses, and the pure functions that turn
//! one into the other. Nothing here touches libbpf; the driver in the parent
//! module owns that.

use std::sync::LazyLock;
use std::sync::mpsc::Receiver;
use std::sync::mpsc::Sender;

use anyhow::Result;

use crate::CgroupStat;
use crate::CpuStat;
use crate::MemoryEvents;
use crate::MemoryEventsLocal;
use crate::MemoryStat;

pub(crate) static PAGE_SIZE: LazyLock<u64> = LazyLock::new(|| {
    // SAFETY: sysconf() with a valid _SC_* name has no preconditions and is
    // thread-safe; _SC_PAGESIZE is always supported, so this never returns -1.
    let page_size = unsafe { libc::sysconf(libc::_SC_PAGESIZE) };
    match page_size {
        -1 => panic!("Failed to query page size"),
        x => x as u64,
    }
});

// Wire record + valid-bit indices, generated by bindgen from the shared C header
// src/bpf/cgroup_bpf_record.h so the Rust and BPF definitions can never drift.
// This pulls in `cgroup_bpf_record` (the struct) and the `CGROUP_FILES_*` bit
// indices into `valid` (enum cgroup_files). The fbcode build gets them from the
// `rust_bindgen_library` (the `cgroup_bpf_record` crate); the open-source build
// generates them at compile time with bindgen in build.rs.
#[cfg(fbcode_build)]
pub(crate) use ::cgroup_bpf_record::*;

#[cfg(not(fbcode_build))]
pub(crate) use super::open_source::*;

/// The wire record (bindgen-generated `cgroup_bpf_record`). bindgen asserts its
/// layout, so no size check is needed here. The `ms_*` fields are FINAL
/// memory.stat values (already in the file's output unit) that `decode_record`
/// copies verbatim; a field of `u64::MAX` means "unavailable" (see the header).
pub(crate) type CgroupBpfRecord = cgroup_bpf_record;

/// `is_valid` reports whether BPF supplied a given `cgroup_files` group for this
/// cgroup (its bit in `valid` is set). It is an extension trait rather than an
/// inherent method because `CgroupBpfRecord` is bindgen-generated -- a foreign
/// type in the fbcode build, which the orphan rule bars an inherent `impl` on.
pub(crate) trait CgroupBpfRecordExt {
    fn is_valid(&self, file: u32) -> bool;
}

impl CgroupBpfRecordExt for CgroupBpfRecord {
    fn is_valid(&self, file: u32) -> bool {
        self.valid & (1 << file) != 0
    }
}

/// Give the (user_ns, system_ns) split that cpu.stat reports, computed like the
/// kernel's `cputime_adjust()`: scale the raw bstat utime/stime to sum to
/// `sum_exec_runtime`, keeping their ratio (cpu.stat prints these scaled values,
/// not the raw utime/stime). We skip the kernel's stateful monotonicity clamp, so
/// the split can drift a few percent on long-running cgroups; the sum stays exact,
/// so usage and rates are unaffected. Nanoseconds in and out.
pub(crate) fn adjust_cputime(utime_ns: u64, stime_ns: u64, rtime_ns: u64) -> (u64, u64) {
    if utime_ns == 0 {
        (0, rtime_ns)
    } else if stime_ns == 0 {
        (rtime_ns, 0)
    } else {
        let total = utime_ns as u128 + stime_ns as u128;
        // 128-bit intermediate: stime_ns * rtime_ns can overflow u64.
        let stime_adj = (stime_ns as u128 * rtime_ns as u128 / total) as u64;
        (rtime_ns.saturating_sub(stime_adj), stime_adj)
    }
}

/// Decode one BPF record into the below-side stat: cputime_adjust scaling, ns->us,
/// memory.current pages->bytes, and honor the `valid` bitmask (a clear bit ->
/// `None`, so the collector reads that file). memory.stat values are already in
/// the file's unit (from the memcg kfuncs), so they are copied as is.
pub(crate) fn decode_record(rec: &CgroupBpfRecord) -> CgroupBpfStat {
    let cpu_stat = if rec.is_valid(CGROUP_FILES_CPU_USAGE) {
        let has_throttle = rec.is_valid(CGROUP_FILES_CPU_THROTTLE);
        let (user_ns, system_ns) = adjust_cputime(
            rec.cpu_utime_ns,
            rec.cpu_stime_ns,
            rec.cpu_sum_exec_runtime_ns,
        );
        Some(CpuStat {
            usage_usec: Some(rec.cpu_sum_exec_runtime_ns / 1000),
            user_usec: Some(user_ns / 1000),
            system_usec: Some(system_ns / 1000),
            nr_periods: has_throttle.then_some(rec.cpu_nr_periods),
            nr_throttled: has_throttle.then_some(rec.cpu_nr_throttled),
            throttled_usec: has_throttle.then_some(rec.cpu_throttled_time_ns / 1000),
        })
    } else {
        None
    };

    let memory_current = if rec.is_valid(CGROUP_FILES_MEM_CURRENT) {
        Some(rec.memory_current_pages.saturating_mul(*PAGE_SIZE) as i64)
    } else {
        None
    };

    let memory_stat = if rec.is_valid(CGROUP_FILES_MEM_STAT) {
        Some(decode_memory_stat(rec))
    } else {
        None
    };

    let cgroup_stat = if rec.is_valid(CGROUP_FILES_CGROUP_STAT) {
        Some(CgroupStat {
            nr_descendants: Some(rec.cgroup_nr_descendants as u32),
            nr_dying_descendants: Some(rec.cgroup_nr_dying_descendants as u32),
        })
    } else {
        None
    };

    // memory.events / .local: low..oom_kill from BPF. The newer `sock_throttled`
    // line is left None, and on a kernel that has it the whole group is skipped
    // (see coverage.rs), so this None never shows against a file that has it.
    let has_events = rec.is_valid(CGROUP_FILES_MEM_EVENTS);
    let memory_events = has_events.then_some(MemoryEvents {
        low: Some(rec.me_low),
        high: Some(rec.me_high),
        max: Some(rec.me_max),
        oom: Some(rec.me_oom),
        oom_kill: Some(rec.me_oom_kill),
        sock_throttled: None,
    });
    let memory_events_local = has_events.then_some(MemoryEventsLocal {
        low: Some(rec.mel_low),
        high: Some(rec.mel_high),
        max: Some(rec.mel_max),
        oom: Some(rec.mel_oom),
        oom_kill: Some(rec.mel_oom_kill),
        sock_throttled: None,
    });

    // memory.{min,low,high,max} limits + memory.oom.group.
    let has_limits = rec.is_valid(CGROUP_FILES_MEM_LIMITS);
    let lim = |raw: u64| -> i64 {
        // A page_counter limit == PAGE_COUNTER_MAX prints as "max" (below: -1);
        // otherwise the file prints raw pages * PAGE_SIZE (bytes).
        if raw >= page_counter_max() {
            -1
        } else {
            raw.saturating_mul(*PAGE_SIZE) as i64
        }
    };
    let memory_min = has_limits.then(|| lim(rec.mem_min));
    let memory_low = has_limits.then(|| lim(rec.mem_low));
    let memory_high = has_limits.then(|| lim(rec.mem_high));
    let memory_max = has_limits.then(|| lim(rec.mem_max));
    let memory_oom_group = has_limits.then_some(rec.mem_oom_group as u32);

    CgroupBpfStat {
        parent_id: rec.parent_id,
        cpu_stat,
        memory_current,
        memory_stat,
        cgroup_stat,
        memory_events,
        memory_events_local,
        memory_min,
        memory_low,
        memory_high,
        memory_max,
        memory_oom_group,
    }
}

/// PAGE_COUNTER_MAX on 64-bit kernels (`LONG_MAX / PAGE_SIZE`). A page_counter
/// limit set to this value is printed as "max" by the cgroupfs file (which below
/// maps to -1), so `decode_record` treats it as the "max" sentinel.
fn page_counter_max() -> u64 {
    (i64::MAX as u64) / *PAGE_SIZE
}

/// Build `MemoryStat` from a record. The `ms_*` values are already in
/// memory.stat's unit (from the memcg kfuncs), so they are copied verbatim. A
/// field carrying the `u64::MAX` "unavailable" sentinel becomes `None`, matching
/// the file omitting untracked lines.
fn decode_memory_stat(rec: &CgroupBpfRecord) -> MemoryStat {
    // u64::MAX marks a counter the kernel does not track -> None; any other value
    // is real (0 included) -> Some, copied as is.
    let ms = |val: u64| -> Option<u64> { (val != u64::MAX).then_some(val) };
    // slab is the file's computed sum of the two slab components.
    let slab = match (ms(rec.ms_slab_reclaimable), ms(rec.ms_slab_unreclaimable)) {
        (Some(a), Some(b)) => Some(a.saturating_add(b)),
        _ => None,
    };
    MemoryStat {
        anon: ms(rec.ms_anon),
        file: ms(rec.ms_file),
        kernel: ms(rec.ms_kernel),
        kernel_stack: ms(rec.ms_kernel_stack),
        slab,
        sock: ms(rec.ms_sock),
        shmem: ms(rec.ms_shmem),
        zswap: ms(rec.ms_zswap),
        zswapped: ms(rec.ms_zswapped),
        file_mapped: ms(rec.ms_file_mapped),
        file_dirty: ms(rec.ms_file_dirty),
        file_writeback: ms(rec.ms_file_writeback),
        swapcached: ms(rec.ms_swapcached),
        file_thp: ms(rec.ms_file_thp),
        anon_thp: ms(rec.ms_anon_thp),
        shmem_thp: ms(rec.ms_shmem_thp),
        inactive_anon: ms(rec.ms_inactive_anon),
        active_anon: ms(rec.ms_active_anon),
        inactive_file: ms(rec.ms_inactive_file),
        active_file: ms(rec.ms_active_file),
        unevictable: ms(rec.ms_unevictable),
        slab_reclaimable: ms(rec.ms_slab_reclaimable),
        slab_unreclaimable: ms(rec.ms_slab_unreclaimable),
        hugetlb: ms(rec.ms_hugetlb),
        pgfault: ms(rec.ms_pgfault),
        pgmajfault: ms(rec.ms_pgmajfault),
        workingset_refault_anon: ms(rec.ms_workingset_refault_anon),
        workingset_refault_file: ms(rec.ms_workingset_refault_file),
        workingset_activate_anon: ms(rec.ms_workingset_activate_anon),
        workingset_activate_file: ms(rec.ms_workingset_activate_file),
        workingset_restore_anon: ms(rec.ms_workingset_restore_anon),
        workingset_restore_file: ms(rec.ms_workingset_restore_file),
        workingset_nodereclaim: ms(rec.ms_workingset_nodereclaim),
        pgrefill: ms(rec.ms_pgrefill),
        pgscan: ms(rec.ms_pgscan),
        pgsteal: ms(rec.ms_pgsteal),
        pgactivate: ms(rec.ms_pgactivate),
        pgdeactivate: ms(rec.ms_pgdeactivate),
        pglazyfree: ms(rec.ms_pglazyfree),
        pglazyfreed: ms(rec.ms_pglazyfreed),
        thp_fault_alloc: ms(rec.ms_thp_fault_alloc),
        thp_collapse_alloc: ms(rec.ms_thp_collapse_alloc),
    }
}

/// Per-cgroup stats sourced from BPF and overlaid onto file reads. Every
/// `Option` field falls back to the cgroupfs file when `None` (the kernel could
/// not supply it, or the cgroup was absent from the BPF traversal), so the data
/// is never partial or wrong. `parent_id` is BPF-only metadata with no file
/// equivalent -- the parent cgroup's id, 0 for the root -- so the tree can be
/// rebuilt from a snapshot alone.
#[derive(Clone, Debug, Default)]
pub struct CgroupBpfStat {
    pub parent_id: u64,
    pub cpu_stat: Option<CpuStat>,
    pub memory_current: Option<i64>,
    pub memory_stat: Option<MemoryStat>,
    pub cgroup_stat: Option<CgroupStat>,
    pub memory_events: Option<MemoryEvents>,
    pub memory_events_local: Option<MemoryEventsLocal>,
    pub memory_min: Option<i64>,
    pub memory_low: Option<i64>,
    pub memory_high: Option<i64>,
    pub memory_max: Option<i64>,
    pub memory_oom_group: Option<u32>,
}

/// A sample's BPF-collected cgroup stats, keyed by cgroup id -- which equals the
/// cgroup directory inode `CgroupReader::read_inode_number` returns, so it joins
/// directly against the cgroupfs walk.
pub type CgroupBpfSnapshot = std::collections::HashMap<u64, CgroupBpfStat>;

/// Handle for obtaining a fresh BPF snapshot each sample. It carries only
/// channels, so the collector can request a snapshot without touching libbpf.
/// `collect` sends a request and blocks for the reply; the exchange is 1:1 and
/// in order, so the snapshot always matches this call.
pub struct CgroupBpfHandle {
    req: Sender<()>,
    resp: Receiver<Result<CgroupBpfSnapshot>>,
}

impl CgroupBpfHandle {
    pub fn new(req: Sender<()>, resp: Receiver<Result<CgroupBpfSnapshot>>) -> Self {
        Self { req, resp }
    }

    /// Ask the driver to flush at the cgroup root, traverse the tree, and reply
    /// with the fresh snapshot; block until it arrives. Returns `None` on any
    /// error or if the driver is not running, so the caller falls back to files.
    /// Setup errors surface via the driver's own error channel, so they are
    /// swallowed here to avoid per-sample log spam.
    pub fn collect(&self) -> Option<CgroupBpfSnapshot> {
        if self.req.send(()).is_err() {
            return None;
        }
        match self.resp.recv() {
            Ok(Ok(snapshot)) => Some(snapshot),
            Ok(Err(_)) => None,
            Err(_) => None,
        }
    }
}
