# This job listens for newly pushed tags and will build + upload a dynamically
# linked below binary as well as full debian packages to release assets.
#
# Note that any consumers of the binary must be compatible with the base image
# in `Dockerfile`.

name: Release

on:
  push:
    tags:
      - "v*.*.*-avx"

permissions:
  contents: write

jobs:
  build-upload:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build binary
      run: |
        docker build -t below .
        mkdir -p output
        docker run -v $(pwd)/output:/output --entrypoint /bin/bash below -c "cp /below /output"

    - name: Build 18.04 debian
      run: |
        ./scripts/build_deb.sh 18.04

    - name: Build 22.04 debian
      run: |
        ./scripts/build_deb.sh 22.04

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref_name }}
        body: |
          Note the binary artifact is dynamically linked.
          Please check the base image used in the `Dockerfile` for compability with your system.
        generate_release_notes: true
        files: |
          ./output/below
          ./*.deb

    - name: Get Token
      id: get_workflow_token
      uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db # v2.1.0
      with:
        application_id: ${{ secrets.AVX_WORKFLOW_APPLICATION_ID }}
        application_private_key: ${{ secrets.AVX_WORKFLOW_APPLICATION_PRIVATE_KEY }}

    # Enable CD and trigger the build of the associated docker image
    # see https://github.com/AvxSre/docker-images
    - name: Trigger docker image build
      env:
        GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
      run: |
        gh workflow run -R AvxSre/docker-images docker.yml -f "image=tracelogs-analyzer"
